spring.application.name=spyfall
server.port=80
#server.port=8083
server.address=0.0.0.0
app.linux.url=http://43.208.205.45
app.linux.folder=/home/ec2-user/masoi
app.win=/src/main/resources/picture
app.phone=/sdcard/java